In [10]:
from keras.datasets import mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train = x_train/255.0
x_test = x_test/255.0
X_train = x_train.reshape(len(x_train),-1)
X_test = x_test.reshape(len(x_test),-1)

In [11]:
from sklearn.cluster import MiniBatchKMeans
import numpy as np
total_clusters = len(np.unique(y_test))

kmeans = MiniBatchKMeans(n_clusters=total_clusters)
kmeans.fit(X_train)
kmeans.labels_

array([0, 3, 8, ..., 0, 7, 9], shape=(60000,), dtype=int32)

In [12]:
def retrieve_info(cluster_labels, y_train):
    """
    Associates most probable class to each cluster
    :param cluster_labels:
    :param y_train:
    :return: dictionary of clusters assigned to each label
    """
    reference_labels = {}

    for i in range(len(np.unique(kmeans.labels_))):
        index = np.where(cluster_labels == i,1,0)
        num = np.bincount(y_train[index == 1]).argmax()
        reference_labels[i] = num

    return reference_labels

reference_labels = retrieve_info(kmeans.labels_,y_train)
number_labels = np.random.rand(len(kmeans.labels_))
for i in range(len(kmeans.labels_)):
    number_labels[i] = reference_labels[kmeans.labels_[i]]

print(number_labels[:20].astype("int"))
print(y_train[:20])

[3 0 4 1 7 2 1 3 1 7 3 1 3 6 1 7 2 7 6 7]
[5 0 4 1 9 2 1 3 1 4 3 5 3 6 1 7 2 8 6 9]


In [13]:
from sklearn import metrics
print(metrics.accuracy_score(number_labels,y_train))

0.5398833333333334
